approvedGitRepositories:
  - "**"

changesetBaseRefs:
  - origin/8.2
  - composer/8.2

changesetIgnorePatterns:
  - .yarn/**/*

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmAlwaysAuth: false

npmAuthToken: "${NPM_TOKEN-}"

npmMinimalAgeGate: 0

npmPublishAccess: public

packageExtensions:
  isemail@3.2.0:
    dependencies:
      buffer: ^5.0.0

patchFolder: ./patches

plugins:
  - ./legacyDependencies.js

yarnPath: .yarn/releases/yarn-4.16.0.cjs
