name: Client (JavaScript)

on:
  workflow_dispatch:
  push:
    branches: [ '[0-9]+.[0-9]' ]
  pull_request:
    branches: [ '[0-9]+.[0-9]' ]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    name: 'Code style'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install
        run: make install-and-verify
      - name: Lint
        run: make lint
      - name: Run production build
        run: make build-production
      - name: Run NPM build of sub-packages
        run: make build-subpackages

  unittests:
    runs-on: ubuntu-latest
    name: 'Unit tests'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install
        run: make install-and-verify
      - name: Test
        run: make test
